"""Remove exam_id from ExamRequest

Revision ID: f60407d1d205
Revises: 410f6b63cced
Create Date: 2024-11-26 21:29:29.071406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f60407d1d205'
down_revision: Union[str, None] = '410f6b63cced'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('exam_requests_exam_id_fkey', 'exam_requests', type_='foreignkey')
    op.drop_column('exam_requests', 'exam_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_requests', sa.Column('exam_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('exam_requests_exam_id_fkey', 'exam_requests', 'exams', ['exam_id'], ['id'])
    # ### end Alembic commands ###
